# Be sure to restart your server when you modify this file.

development:
  fiber_api_key: <%= ENV["FIBER_API_KEY"] %>
  fiber_device_id: <%= ENV["FIBER_DEVICE_ID"] %>
  secret_key_base: ea10e0a0200e6bac696b5251def4aec082df108df6ff53a60e8ce9ec7ab547a1e086ea8151106a42b86262f9444535664bec86499d689995b0abf6443068f652

test:
  fiber_api_key: <%= ENV["FIBER_API_KEY"] %>
  fiber_device_id: <%= ENV["FIBER_DEVICE_ID"] %>
  secret_key_base: d65597f75ea14a42521659bbb241aa6ecc1dc751c0323be6fb5e2f7772dc628e05665acf8d48af8f51309d6f5d32a726c176bb70c28063e684a02d25c5401e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  fiber_api_key: <%= ENV["FIBER_API_KEY"] %>
  fiber_device_id: <%= ENV["FIBER_DEVICE_ID"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
